// The scene and widget pages are generated by obs/build-scenes.py: the committed pages must be what it writes, or the next
// build silently undoes a hand edit (or the build has changed and nobody ran it).
import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, readdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { ROOT } from '../helpers/sim.mjs';

test('public/obs scene pages match a fresh obs/build-scenes.py', (t) => {
  const out = mkdtempSync(join(tmpdir(), 'tgl-scenes-'));
  try {
    try { execFileSync('python3', [ROOT + 'obs/build-scenes.py'], { env: { ...process.env, TGL_OBS_OUT: out }, stdio: 'ignore' }); }
    catch (e) { if (e.code === 'ENOENT') return t.skip('python3 not available'); throw e; }
    const built = readdirSync(out).filter((f) => f.endsWith('.html'));
    assert.deepEqual(built.sort(), ['brb.html', 'chat.html', 'chatting.html', 'ending.html', 'game.html', 'goal.html', 'music.html', 'starting.html']);
    for (const f of built) assert.equal(readFileSync(join(ROOT, 'public/obs', f), 'utf8'), readFileSync(join(out, f), 'utf8'), `${f} differs from what build-scenes.py writes: edit the template, then run python3 obs/build-scenes.py`);
  } finally { rmSync(out, { recursive: true, force: true }); }
});
